### ISSUE TITLE
eLabFTW Integration 2

### ISSUE THREAD

**Issue by manulera** [manulera/OpenCloning#36]
Followup to #33 

Hi @NicolasCARPi,

I finished up most things for the plugin. There are a few things left (see below), but I think with this you can already add it to the demo instance.

## Docker Compose settings

Some new settings have been added

```yaml
  opencloning-plugin:
    image: manulera/opencloning:v0.5-baseurl-opencloning
    container_name: opencloning-plugin
    restart: always
    networks:
      - elabftw-net
    environment:
      - ALLOWED_ORIGINS=*
      - ROOT_PATH=/opencloning
      - BACKEND_URL=/opencloning/
      - SHOW_APP_BAR=false # hide the app bar in the plugin (default is true)
      - DATABASE=elabftw # the database to use (use elabtfw, default is empty)
```

## What I have fixed so far

* The app bar can now be hidden.
* Loading from url: you can load files from the url using query parameters like this `?source=database&item_id=7&file_id=10`. However, I don't think I can access the query parameters from the iframe. It works from my dev server using API keys, but not from the iframe.
* If API keys are not defined in env vars, it no longer sends an empty Authorization header, it just doesn't send the header at all.
* Renamed the flag extension of the images to `-baseurl-opencloning` (you should use those).
* You can now load history files (.json), which also load the history of the sequence up to the closest ancestors store in the database (see video at bottom).
* You can also keep loading further history (see video at bottom).
* When loading a json history file, if the names of the primers in the database have changed with respect to the names in the json file, the newer names will be displayed.
* When trying to save a sequence with unsaved ancestors (e.g. a PCR product that the user probably does not want to save), there is a warning explaining what will happen (see video at bottom).
* You can select which icons will be displayed in the corner for saving to the database, and when the item is saved. I am currently using the floppy disk for saving and the link for when the item is saved, but we can change it (see video at bottom).
* If a request fails when trying to save primers or sequences, the transient entities are deleted.

## Me: TODO
* [ ] Handle the case where items have been deleted:
  * [ ] When a primer has been deleted, we currently will be trying to read the name from the database giving an error.
  * [ ] Should also give an error if the primer sequence has changed.
  * [ ] When a sequence has been deleted and you tried to load it as an ancestor, there is now now meaningful error message.
* [ ] Loading the same primer twice. Currently, there is a restriction that two primers with the same name cannot be loaded. However, when loading two histories, if they contain the same primer (same database id), it should be possible to load them into a single primer.
* [ ] Add support for sequencing files.
* [ ] Write tests.
* [ ] Auto-load (don't worry about this)

## You: TODO
* [ ] Allow popups from the iframe so that the links to the resources open in a new tab. Currently I get this error

```
opencloning/:1 Blocked opening 'https://localhost/database.php?mode=view&id=3' in a new window because the request was made in a sandboxed frame whose 'allow-popups' permission is not set.
```

* [ ] Allow the iframe to access the query parameters of the parent page.

## Video (has sound)

https://github.com/user-attachments/assets/093edc6b-347d-402f-8adf-c5363b95adc9
